set(_CATKIN_CURRENT_PACKAGE "move_videoray")
set(move_videoray_MAINTAINER "nathaniel <nathaniel@todo.todo>")
set(move_videoray_DEPRECATED "")
set(move_videoray_VERSION "0.0.0")
set(move_videoray_BUILD_DEPENDS "geometry_msgs" "pcl_conversions" "pcl_ros" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(move_videoray_RUN_DEPENDS "geometry_msgs" "pcl_conversions" "pcl_ros" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(move_videoray_BUILDTOOL_DEPENDS "catkin")