set(_CATKIN_CURRENT_PACKAGE "abandonedmarina")
set(abandonedmarina_MAINTAINER "unnar <unnar@kth.se>")
set(abandonedmarina_DEPRECATED "")
set(abandonedmarina_VERSION "0.0.0")
set(abandonedmarina_BUILD_DEPENDS "geometry_msgs" "pcl_conversions" "pcl_ros" "roscpp" "rospy" "sensor_msgs" "visualization_msgs" "std_msgs" "nav_msgs" "tf" "tf_conversions" "eigen_conversions" "message_generation" "message_runtime" "mapclasses")
set(abandonedmarina_RUN_DEPENDS "geometry_msgs" "pcl_conversions" "pcl_ros" "roscpp" "rospy" "sensor_msgs" "visualization_msgs" "std_msgs" "nav_msgs" "tf" "tf_conversion" "eigen_conversion" "message_generation" "message_runtime" "mapclasses")
set(abandonedmarina_BUILDTOOL_DEPENDS "catkin")